### ISSUE TITLE
Font links in CSS file don't have hash suffix

### ISSUE THREAD

**Issue by denis-ok** [denis-ok/rescript-ssg#4]
For example, we have the following CSS file and a code:

```css
@font-face {
  font-family: "MyFont";
  src: url("./my-font.woff2");
  font-display: swap;
}
```

```reason
[@module "./fonts.css"] external fontsCss: string = "default";
[@module "./my-font.woff2"] external myFont: string = "default";

// injecting meta tags with React Helmet
<link rel="preload" type_="font/woff2" href=myFont />
<link rel="stylesheet" href=fonts.css />
```

Since CSS file is an asset, it won't be processed so the link to the font will be broken since it doesn't have a hash suffix.
[CSS loader](https://webpack.js.org/loaders/css-loader/) for Webpack should help with it.
